"""
preprocessing/comparison.py

Computes empirical Before vs After preprocessing comparison statistics:
- Overall dataset metrics: rows, columns, missing values, duplicates, outliers
- Column-level metrics: missing counts & %, outlier counts & %, numerical summary stats
- Distribution histograms: 10-bin distribution before vs after for numerical features
- Category frequencies: before vs after category counts for categorical features
"""
import math
import numpy as np
import pandas as pd
from typing import Dict, Any, List, Optional


def compute_preprocessing_comparison(
    df_raw: pd.DataFrame,
    df_cleaned: pd.DataFrame,
    preprocessor: Optional[Any] = None
) -> Dict[str, Any]:
    """
    Computes side-by-side empirical comparison statistics between raw and cleaned DataFrames.

    Parameters
    ----------
    df_raw : pd.DataFrame
        Original uncleaned dataset.
    df_cleaned : pd.DataFrame
        Imputed / preprocessed dataset generated by HybridPreprocessor.transform_cleaned().
    preprocessor : Optional[HybridPreprocessor]
        Fitted HybridPreprocessor instance to inspect decision plan & strategies.

    Returns
    -------
    dict
        Structured comparison payload with 'overall' and 'columns' dictionaries.
    """
    total_raw_rows = int(len(df_raw))
    total_clean_rows = int(len(df_cleaned))
    total_raw_missing = int(df_raw.isna().sum().sum())
    total_clean_missing = int(df_cleaned.isna().sum().sum())
    total_raw_duplicates = int(df_raw.duplicated().sum())
    total_clean_duplicates = int(df_cleaned.duplicated().sum())

    # Decision strategies lookup
    col_strategies = {}
    if preprocessor is not None and hasattr(preprocessor, "decision_plan_") and preprocessor.decision_plan_:
        plan_cols = preprocessor.decision_plan_.get("columns", [])
        for c in plan_cols:
            name = c.get("column_name")
            strat = c.get("strategy") or c.get("imputation_strategy") or c.get("status")
            if name:
                col_strategies[name] = strat

    # Total outlier counters
    total_raw_outliers = 0
    total_clean_outliers = 0

    column_comparisons = {}
    # Retain common columns
    common_cols = [c for c in df_raw.columns if c in df_cleaned.columns]

    for col in common_cols:
        s_raw = df_raw[col]
        s_clean = df_cleaned[col]

        raw_missing = int(s_raw.isna().sum())
        clean_missing = int(s_clean.isna().sum())

        raw_missing_pct = round((raw_missing / total_raw_rows) * 100, 2) if total_raw_rows > 0 else 0.0
        clean_missing_pct = round((clean_missing / total_clean_rows) * 100, 2) if total_clean_rows > 0 else 0.0

        is_num = pd.api.types.is_numeric_dtype(s_clean) and not pd.api.types.is_bool_dtype(s_clean)

        strat_label = col_strategies.get(col)

        if is_num:
            s_raw_valid = pd.to_numeric(s_raw, errors="coerce").dropna()
            s_clean_valid = pd.to_numeric(s_clean, errors="coerce").dropna()

            # Outlier counts via IQR
            raw_outliers = 0
            if len(s_raw_valid) >= 5:
                q1 = float(s_raw_valid.quantile(0.25))
                q3 = float(s_raw_valid.quantile(0.75))
                iqr = q3 - q1
                if iqr > 0:
                    raw_outliers = int(((s_raw_valid < (q1 - 1.5 * iqr)) | (s_raw_valid > (q3 + 1.5 * iqr))).sum())

            clean_outliers = 0
            if len(s_clean_valid) >= 5:
                q1_c = float(s_clean_valid.quantile(0.25))
                q3_c = float(s_clean_valid.quantile(0.75))
                iqr_c = q3_c - q1_c
                if iqr_c > 0:
                    clean_outliers = int(((s_clean_valid < (q1_c - 1.5 * iqr_c)) | (s_clean_valid > (q3_c + 1.5 * iqr_c))).sum())

            total_raw_outliers += raw_outliers
            total_clean_outliers += clean_outliers

            # Summary stats
            r_min = float(s_raw_valid.min()) if len(s_raw_valid) > 0 else 0.0
            r_max = float(s_raw_valid.max()) if len(s_raw_valid) > 0 else 0.0
            r_mean = float(s_raw_valid.mean()) if len(s_raw_valid) > 0 else 0.0
            r_median = float(s_raw_valid.median()) if len(s_raw_valid) > 0 else 0.0
            r_std = float(s_raw_valid.std()) if len(s_raw_valid) > 1 else 0.0
            r_skew = float(s_raw_valid.skew()) if len(s_raw_valid) > 2 else 0.0

            c_min = float(s_clean_valid.min()) if len(s_clean_valid) > 0 else 0.0
            c_max = float(s_clean_valid.max()) if len(s_clean_valid) > 0 else 0.0
            c_mean = float(s_clean_valid.mean()) if len(s_clean_valid) > 0 else 0.0
            c_median = float(s_clean_valid.median()) if len(s_clean_valid) > 0 else 0.0
            c_std = float(s_clean_valid.std()) if len(s_clean_valid) > 1 else 0.0
            c_skew = float(s_clean_valid.skew()) if len(s_clean_valid) > 2 else 0.0

            if not strat_label:
                strat_label = "Median Imputation" if abs(r_skew) > 1.0 else "Mean Imputation"

            # 10 Bins histogram
            overall_min = min(r_min, c_min)
            overall_max = max(r_max, c_max)

            if overall_min == overall_max:
                bin_edges = np.array([overall_min - 0.5, overall_max + 0.5])
            else:
                bin_edges = np.linspace(overall_min, overall_max, 11)

            counts_raw, _ = np.histogram(s_raw_valid, bins=bin_edges)
            counts_clean, _ = np.histogram(s_clean_valid, bins=bin_edges)

            histogram_data = []
            for i in range(len(bin_edges) - 1):
                b_start = round(float(bin_edges[i]), 2)
                b_end = round(float(bin_edges[i + 1]), 2)
                histogram_data.append({
                    "range": f"{b_start} to {b_end}",
                    "before_count": int(counts_raw[i]),
                    "after_count": int(counts_clean[i]),
                })

            column_comparisons[col] = {
                "name": col,
                "type": "numeric",
                "strategy": strat_label,
                "before": {
                    "missing": raw_missing,
                    "missing_pct": raw_missing_pct,
                    "outliers": raw_outliers,
                    "min": round(r_min, 4) if not math.isnan(r_min) else None,
                    "max": round(r_max, 4) if not math.isnan(r_max) else None,
                    "mean": round(r_mean, 4) if not math.isnan(r_mean) else None,
                    "median": round(r_median, 4) if not math.isnan(r_median) else None,
                    "std": round(r_std, 4) if not math.isnan(r_std) else None,
                    "skewness": round(r_skew, 4) if not math.isnan(r_skew) else None,
                },
                "after": {
                    "missing": clean_missing,
                    "missing_pct": clean_missing_pct,
                    "outliers": clean_outliers,
                    "min": round(c_min, 4) if not math.isnan(c_min) else None,
                    "max": round(c_max, 4) if not math.isnan(c_max) else None,
                    "mean": round(c_mean, 4) if not math.isnan(c_mean) else None,
                    "median": round(c_median, 4) if not math.isnan(c_median) else None,
                    "std": round(c_std, 4) if not math.isnan(c_std) else None,
                    "skewness": round(c_skew, 4) if not math.isnan(c_skew) else None,
                },
                "histogram": histogram_data,
            }
        else:
            # Categorical column
            if not strat_label:
                strat_label = "Mode Imputation (Frequent)"

            top_raw = s_raw.fillna("(Missing)").astype(str).value_counts()
            top_clean = s_clean.fillna("(Missing)").astype(str).value_counts()

            # Top 8 categories
            top_cats = list(top_raw.head(8).index)
            cat_list = []
            for cat_name in top_cats:
                cat_list.append({
                    "category": str(cat_name),
                    "before_count": int(top_raw.get(cat_name, 0)),
                    "after_count": int(top_clean.get(cat_name, 0)),
                })

            column_comparisons[col] = {
                "name": col,
                "type": "categorical",
                "strategy": strat_label,
                "before": {
                    "missing": raw_missing,
                    "missing_pct": raw_missing_pct,
                    "unique_count": int(s_raw.nunique()),
                },
                "after": {
                    "missing": clean_missing,
                    "missing_pct": clean_missing_pct,
                    "unique_count": int(s_clean.nunique()),
                },
                "categories": cat_list,
            }

    missing_resolved_pct = (
        100.0 if total_raw_missing == 0
        else round(((total_raw_missing - total_clean_missing) / total_raw_missing) * 100, 2)
    )

    return {
        "overall": {
            "before": {
                "rows": total_raw_rows,
                "columns": len(df_raw.columns),
                "missing_values": total_raw_missing,
                "duplicate_rows": total_raw_duplicates,
                "outliers": total_raw_outliers,
            },
            "after": {
                "rows": total_clean_rows,
                "columns": len(df_cleaned.columns),
                "missing_values": total_clean_missing,
                "duplicate_rows": total_clean_duplicates,
                "outliers": total_clean_outliers,
            },
            "missing_resolved_pct": missing_resolved_pct,
        },
        "columns": column_comparisons,
    }
